#!/usr/bin/env bash
set -euo pipefail

# Check argument
if [ $# -lt 1 ] || [ -z "$1" ]; then
    echo "Usage: $0 <tps2-commit-sha>" >&2
    exit 1
fi

SHA="$1"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET_FILE="${REPO_ROOT}/src-tauri/src/tps2_types.rs"

# Ensure cargo-typify is available
if ! command -v cargo-typify &> /dev/null; then
    echo "cargo-typify not found. Installing cargo-typify..."
    cargo install cargo-typify
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "${TMP_DIR}"' EXIT

SWAGGER_FILE="${TMP_DIR}/iam.swagger.json"
RAW_OUTPUT_FILE="${TMP_DIR}/output.rs"

echo "Fetching iam.swagger.json from NumaxTPS2/TPS2 at commit ${SHA}..."
gh api -H "Accept: application/vnd.github.v3.raw" "repos/NumaxTPS2/TPS2/contents/api/docs/iam.swagger.json?ref=${SHA}" > "${SWAGGER_FILE}"

echo "Generating Rust types with typify..."
cargo typify "${SWAGGER_FILE}" -o "${RAW_OUTPUT_FILE}"

echo "Writing generated types to ${TARGET_FILE}..."
cat <<EOF > "${TARGET_FILE}"
// Code generated by scripts/gen-types.sh from NumaxTPS2/TPS2 commit ${SHA}. DO NOT EDIT.

EOF

cat "${RAW_OUTPUT_FILE}" >> "${TARGET_FILE}"

echo "Successfully generated ${TARGET_FILE} from commit ${SHA}."
